#!/usr/bin/env bun
import {
  emitResult,
  globalOptions,
  success,
  usage,
} from "./aidlc-command.ts";
import { listRoutes } from "./aidlc.ts";

export type Shell = "bash" | "zsh" | "fish" | "powershell";

type CompletionInventory = {
  top: string[];
  nouns: Record<string, string[]>;
  options: Record<string, string[]>;
};

const GLOBAL_OPTIONS = ["--no-color"];

function routeOptions(
  route: ReturnType<typeof listRoutes>[number],
  verb: string,
): string[] {
  const values = new Set(GLOBAL_OPTIONS);
  if (route.outputModes.includes("json")) values.add("--json");
  if (route.outputModes.includes("quiet")) values.add("--quiet");
  if (route.networkPolicy !== "forbidden") values.add("--offline");
  for (
    const line of (route.all ?? []).filter((value) =>
      value.split(/\s+/, 1)[0] === verb
    )
  ) {
    for (const option of line.match(/--[a-z][a-z-]*/g) ?? []) values.add(option);
  }
  return [...values].sort();
}

function inventory(): CompletionInventory {
  const routes = listRoutes().filter((route) =>
    route.visibility === "public" && route.classification !== "stub"
  );
  const top = new Set<string>();
  const nouns: Record<string, string[]> = {};
  const options: Record<string, string[]> = {};
  for (const route of routes) {
    const verbs = route.verbs.filter((verb) =>
      !verb.startsWith("<") && !verb.startsWith("__")
    );
    if (route.group === "top") {
      for (const verb of verbs) {
        top.add(verb);
        const routeOptionValues = routeOptions(route, verb);
        options[verb] = [...new Set([
          ...(options[verb] ?? []),
          ...routeOptionValues,
        ])].sort();
      }
      continue;
    }
    if (!nouns[route.group]) nouns[route.group] = [];
    top.add(route.group);
    for (const verb of verbs) {
      const first = verb.split(/\s+/, 1)[0];
      const routeOptionValues = routeOptions(route, first);
      nouns[route.group].push(first);
      const key = `${route.group} ${first}`;
      options[key] = [...new Set([
        ...(options[key] ?? []),
        ...routeOptionValues,
      ])].sort();
    }
  }
  for (const noun of Object.keys(nouns)) {
    nouns[noun] = [...new Set(nouns[noun])].sort();
  }
  return { top: [...top].sort(), nouns, options };
}

function bashCase(rows: Record<string, string[]>, indent: string): string {
  return Object.entries(rows)
    .map(([key, values]) => `${indent}'${key}') words="${values.join(" ")}" ;;`)
    .join("\n");
}

function bash(data: CompletionInventory): string {
  return `# generated by the AI-DLC installer
_aidlc_completions() {
  local cur="\${COMP_WORDS[COMP_CWORD]}" words="" key
  if [ "\${COMP_CWORD}" -eq 1 ]; then
    words="${data.top.join(" ")}"
  elif [[ "$cur" == --* ]]; then
    key="\${COMP_WORDS[1]}"
    [ "\${COMP_CWORD}" -ge 3 ] && key="$key \${COMP_WORDS[2]}"
    case "$key" in
${bashCase(data.options, "      ")}
    esac
  elif [ "\${COMP_CWORD}" -eq 2 ]; then
    case "\${COMP_WORDS[1]}" in
${bashCase(data.nouns, "      ")}
    esac
  fi
  COMPREPLY=( $(compgen -W "$words" -- "$cur") )
}
complete -F _aidlc_completions aidlc
`;
}

function zshCase(rows: Record<string, string[]>, indent: string): string {
  return Object.entries(rows)
    .map(([key, values]) => `${indent}'${key}') values=(${values.join(" ")}) ;;`)
    .join("\n");
}

function zsh(data: CompletionInventory): string {
  return `#compdef aidlc
# generated by the AI-DLC installer
_aidlc() {
  local -a values
  local key="\${words[2]}"
  if (( CURRENT == 2 )); then
    values=(${data.top.join(" ")})
  elif [[ "\${words[CURRENT]}" == --* ]]; then
    (( CURRENT >= 4 )) && key="$key \${words[3]}"
    case "$key" in
${zshCase(data.options, "      ")}
    esac
  else
    case "\${words[2]}" in
${zshCase(data.nouns, "      ")}
    esac
  fi
  _describe 'aidlc value' values
}
compdef _aidlc aidlc
`;
}

function fish(data: CompletionInventory): string {
  const lines = [
    "# generated by the AI-DLC installer",
    ...data.top.map((command) =>
      `complete -c aidlc -n '__fish_use_subcommand' -a '${command}'`
    ),
  ];
  for (const [noun, verbs] of Object.entries(data.nouns)) {
    for (const verb of verbs) {
      lines.push(
        `complete -c aidlc -n '__fish_seen_subcommand_from ${noun}' -a '${verb}'`,
      );
    }
  }
  const optionNames = [...new Set(Object.values(data.options).flat())].sort();
  for (const option of optionNames) {
    lines.push(`complete -c aidlc -l '${option.slice(2)}'`);
  }
  return `${lines.join("\n")}\n`;
}

function psArray(values: readonly string[]): string {
  return `@(${values.map((value) => `'${value.replaceAll("'", "''")}'`).join(", ")})`;
}

function powershellSwitch(rows: Record<string, string[]>): string {
  return Object.entries(rows)
    .map(([key, values]) =>
      `      '${key.replaceAll("'", "''")}' { ${psArray(values)}; break }`
    )
    .join("\n");
}

function powershell(data: CompletionInventory): string {
  return `# generated by the AI-DLC installer
Register-ArgumentCompleter -Native -CommandName aidlc -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $tokens = @($commandAst.CommandElements | ForEach-Object { $_.Extent.Text })
  $values = if ($tokens.Count -le 2) {
    ${psArray(data.top)}
  } elseif ($wordToComplete.StartsWith('--')) {
    $key = $tokens[1]
    if ($tokens.Count -ge 3) { $key = "$key $($tokens[2])" }
    switch ($key) {
${powershellSwitch(data.options)}
      default { @() }
    }
  } else {
    switch ($tokens[1]) {
${powershellSwitch(data.nouns)}
      default { @() }
    }
  }
  $values | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
  }
}
`;
}

const RENDERERS: Record<Shell, (data: CompletionInventory) => string> = { bash, zsh, fish, powershell };

export function renderCompletion(shell: Shell): string {
  return RENDERERS[shell](inventory());
}

// Rows between a block's opening line and its closing line, or null when any
// line inside is not a row. A block with no rows renders one empty line.
function blockRows(
  lines: readonly string[],
  open: string,
  close: string,
  row: RegExp,
): Record<string, string> | null {
  const start = lines.indexOf(open);
  const end = start === -1 ? -1 : lines.indexOf(close, start + 1);
  if (end === -1) return null;
  const body = lines.slice(start + 1, end);
  const rows: Record<string, string> = {};
  if (body.length === 1 && body[0] === "") return rows;
  for (const line of body) {
    const match = row.exec(line);
    if (!match) return null;
    rows[match[1]] = match[2];
  }
  return rows;
}

function mapRows(
  rows: Record<string, string> | null,
  values: (text: string) => string[] | null,
): Record<string, string[]> | null {
  if (!rows) return null;
  const result: Record<string, string[]> = {};
  for (const [key, text] of Object.entries(rows)) {
    const parsed = values(text);
    if (!parsed) return null;
    result[key] = parsed;
  }
  return result;
}

function psValues(text: string): string[] | null {
  const inner = /^@\((.*)\)$/.exec(text)?.[1];
  if (inner === undefined) return null;
  return [...inner.matchAll(/'((?:[^']|'')*)'/g)].map((match) => match[1].replaceAll("''", "'"));
}

function parsedInventory(shell: Shell, content: string): CompletionInventory | null {
  const lines = content.split("\n");
  const words = (text: string): string[] => text.split(" ");
  if (shell === "fish") {
    const top: string[] = [];
    const nouns: Record<string, string[]> = {};
    const options: string[] = [];
    for (const line of lines.slice(1, -1)) {
      const command = /^complete -c aidlc -n '__fish_use_subcommand' -a '([^']*)'$/.exec(line);
      const verb = /^complete -c aidlc -n '__fish_seen_subcommand_from ([^']*)' -a '([^']*)'$/.exec(line);
      const option = /^complete -c aidlc -l '([^']*)'$/.exec(line);
      if (command) top.push(command[1]);
      else if (verb) nouns[verb[1]] = [...(nouns[verb[1]] ?? []), verb[2]];
      else if (option) options.push(`--${option[1]}`);
      else return null;
    }
    return { top, nouns, options: { "": options } };
  }
  if (shell === "powershell") {
    const top = psValues(lines.find((line) => line.startsWith("    @("))?.slice(4) ?? "");
    const row = /^ {6}'((?:[^']|'')*)' \{ (@\(.*\)); break \}$/;
    const unquoteKeys = (rows: Record<string, string> | null) =>
      rows && Object.fromEntries(Object.entries(rows).map(([key, text]) => [key.replaceAll("''", "'"), text]));
    const options = mapRows(unquoteKeys(blockRows(lines, "    switch ($key) {", "      default { @() }", row)), psValues);
    const nouns = mapRows(unquoteKeys(blockRows(lines, "    switch ($tokens[1]) {", "      default { @() }", row)), psValues);
    return top && options && nouns ? { top, nouns, options } : null;
  }
  const [field, nounsOpen, row] = shell === "bash"
    ? ["words=\"", `    case "\${COMP_WORDS[1]}" in`, /^ {6}'([^']*)'\) words="([^"]*)" ;;$/]
    : ["values=(", `    case "\${words[2]}" in`, /^ {6}'([^']*)'\) values=\(([^)]*)\) ;;$/];
  const topLine = lines.find((line) => line.startsWith(`    ${field}`));
  const top = topLine === undefined ? null : words(topLine.slice(4 + field.length, -1));
  const options = mapRows(blockRows(lines, '    case "$key" in', "    esac", row), words);
  const nouns = mapRows(blockRows(lines, nounsOpen, "    esac", row), words);
  return top && options && nouns ? { top, nouns, options } : null;
}

// Activation writes the completions of the release that runs it, so after an
// update they come from the previous release. Every release renders through
// these templates: content that parses back into a command list and renders
// to the same text is AI-DLC's own, whichever release wrote it, while any
// edited or added byte makes it the person's.
export function isGeneratedCompletion(shell: Shell, content: string): boolean {
  const data = parsedInventory(shell, content);
  if (!data) return false;
  const word = (value: string): boolean => /^(?:--)?[a-z][a-z0-9-]*$/.test(value);
  const key = (value: string): boolean => /^[a-z][a-z0-9-]*(?: [a-z][a-z0-9-]*)?$/.test(value);
  const commandList = data.top.every(word) &&
    Object.entries(data.nouns).every(([noun, verbs]) => key(noun) && verbs.every(word)) &&
    Object.entries(data.options).every(([name, values]) =>
      (shell === "fish" ? name === "" : key(name)) && values.every(word)
    );
  return commandList && RENDERERS[shell](data) === content;
}

export async function main(argv: string[]): Promise<void> {
  const shell = (argv[0] === "completions" ? argv[1] : argv[0]) as Shell | undefined;
  const result = shell && ["bash", "zsh", "fish", "powershell"].includes(shell)
    ? success(renderCompletion(shell), { shell })
    : usage("usage: aidlc system completions <bash|zsh|fish|powershell>");
  if (result.ok && globalOptions(argv).mode === "human") {
    process.stdout.write(result.message);
    process.exitCode = 0;
    return;
  }
  emitResult(result, globalOptions(argv));
}

if (import.meta.main) {
  void main(process.argv.slice(2));
}
